### PR TITLE
fix shutdown database without sync index file header

### LINKED ISSUE #270: [BUG] index was not rebuilt after restarting the database
**Describe the bug**
After restarting the database, I found that the index was not rebuilt.

**Environment**

 
略

**Fast Reproduce Steps(Required)**
```code
create table t(i int);
insert into t values(1);
create index ii on t(i);
select * from t where i=1;
// now result contains one record

//exit and restart

select * from t where i=1;
// now result is empty
```
**Expected behavior**
After restarting and executing select * from t where i=1; , we should get one record .

**Actual Behavior**
In fact, we get nothing.
image

**Additional context**
I suppose this is caused by missing sync of `IndexFileHeader`.
In blus_tree.cpp:BplusTreeHandler::update, header_dirty_  is set to true in update_root_page_num_locked, but never be read, so index header isn't updated.
```
void BplusTreeHandler::update_root_page_num_locked(PageNum root_page_num)
{
  file_header_.root_page = root_page_num;
  header_dirty_          = true;
  LOG_DEBUG("set root page to %d", root_page_num);
}
```

### PR DESCRIPTION
**Pull request by ringfa11**
### What problem were solved in this pull request?

Issue Number: close #270 

Problem: When the database is shut down, the index file header does not sync properly.

### What is changed and how it works?
When the database is shut down，check header_dirty_ flag in BplusTreeHandler, if true, sync the index file.

### CODE REVIEW

File: src/observer/storage/index/bplus_tree.cpp [hunk 1]
```diff
@@ -728,6 +728,19 @@ bool InternalIndexNodeHandler::validate(const KeyComparator &comparator, DiskBuf
 
 RC BplusTreeHandler::sync()
 {
+  if (header_dirty_) {
+    Frame *frame;
+    if (disk_buffer_pool_->get_this_page(FIRST_INDEX_PAGE, &frame) == RC::SUCCESS) {
```
Comment (hnwyllmm) [inline src/observer/storage/index/bplus_tree.cpp:733]: Usually, we want to get the error code. We can print the return value to the log file.

File: src/observer/storage/index/bplus_tree.cpp [hunk 2]
```diff
@@ -728,6 +728,19 @@ bool InternalIndexNodeHandler::validate(const KeyComparator &comparator, DiskBuf
 
 RC BplusTreeHandler::sync()
 {
+  if (header_dirty_) {
+    Frame *frame;
```
Comment (hnwyllmm) [inline src/observer/storage/index/bplus_tree.cpp:732]: Init the value when we declare it.

**Comment by hnwyllmm** [comment]
>
> 
> **linfp** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/miniob?pullRequest=271) it.

You committed the code with wrong author information. Please check the git log information and make sure the email is your github account's email address.
If not, you can change the author with git command. Maybe it is `git amend --author` but I'm not sure.

File: src/observer/storage/index/bplus_tree.cpp (hunk 1 above)
Comment (ringfa11) [reply src/observer/storage/index/bplus_tree.cpp]: Thank you for your reply. 
I have now followed the tips you pointed out.
Now you can review again.

**Review by hnwyllmm — APPROVED** [review]

**Comment by hnwyllmm** [comment]
There are some format issues and I fix them directly.
Thanks for your contribution.
